CREATE DATABASE koolPetrovski
use koolPetrovski

create table opilane (
	opilaneID INT PRIMARY KEY,
	eesnimi VARCHAR(50),
	perenimi VARCHAR(50),
	epost VARCHAR(50),
	sugu VARCHAR(50),
	stip DECIMAL(5,2)
);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (1, 'Maje', 'Keggins', 'mkeggins0@booking.com', 'Male', 76.34);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (2, 'Brenna', 'Ketchell', 'bketchell1@miibeian.gov.cn', 'Female', 44.95);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (3, 'Em', 'Radoux', 'eradoux2@kickstarter.com', 'Male', 43.5);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (4, 'Abey', 'Merali', 'amerali3@macromedia.com', 'Male', 77.68);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (5, 'Helen-elizabeth', 'Keeble', 'hkeeble4@theatlantic.com', 'Female', 29.41);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (6, 'Karlotta', 'Theobald', 'ktheobald5@nsw.gov.au', 'Female', 43.35);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (7, 'Clemmy', 'Christiensen', 'cchristiensen6@ihg.com', 'Male', 7.42);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (8, 'Tine', 'Adacot', 'tadacot7@meetup.com', 'Female', 13.32);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (9, 'Gar', 'Vasyutin', 'gvasyutin8@phoca.cz', 'Male', 42.04);
Collie', 'Kelleher', 'cinsert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (10, 'Donnie', 'Baddow', 'dbaddow9@trellian.com', 'Female', 75.85);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (11, 'Cynthie', 'Tripp', 'ctrippa@ifeng.com', 'Female', 37.03);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (12, 'Orsola', 'Copyn', 'ocopynb@jiathis.com', 'Female', 40.49);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (13, 'Madonna', 'Siney', 'msineyc@slashdot.org', 'Female', 24.67);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (14, 'Marigold', 'McGuggy', 'mmcguggyd@marketwatch.com', 'Female', 28.39);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (15, 'Lindsey', 'Cordy', 'lcordye@bluehost.com', 'Male', 95.8);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (16, 'Viva', 'L'' Anglois', 'vlangloisf@indiatimes.com', 'Female', 80.15);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (17, 'Bondon', 'Van', 'bvang@reuters.com', 'Male', 40.43);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (18, 'Oona', 'Kapiloff', 'okapiloffh@hao123.com', 'Female', 7.47);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (19, 'Elianore', 'Maddin', 'emaddini@admin.ch', 'Female', 99.45);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (20, 'Marcia', 'Wathan', 'mwathanj@amazon.co.jp', 'Female', 15.31);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (21, 'Camey', 'Ulrik', 'culrikk@pinterest.com', 'Male', 36.16);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (22, 'Clary', 'Keneforde', 'ckenefordel@freewebs.com', 'Female', 32.13);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (23, 'Reynold', 'Jacmard', 'rjacmardm@yale.edu', 'Male', 44.58);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (24, 'Chev', 'Tym', 'ctymn@answers.com', 'Male', 74.14);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (25, 'Mendy', 'Wakenshaw', 'mwakenshawo@mac.com', 'Male', 20.84);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (26, 'Hervey', 'Bentinck', 'hbentinckp@cmu.edu', 'Male', 58.2);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (27, 'Loreen', 'Bonsul', 'lbonsulq@thetimes.co.uk', 'Female', 25.29);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (28, 'Claudetta', 'Daouse', 'cdaouser@pen.io', 'Female', 37.99);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (29, 'Marita', 'M''Chirrie', 'mmchirries@amazon.co.uk', 'Female', 6.39);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (30, 'Clarey', 'Cranidge', 'ccranidget@opera.com', 'Female', 68.16);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (31, 'Hew', 'Shovel', 'hshovelu@narod.ru', 'Male', 36.14);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (32, 'Ulric', 'Naptin', 'unaptinv@geocities.com', 'Male', 31.19);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (33, 'Sargent', 'Childrens', 'schildrensw@infoseek.co.jp', 'Male', 98.8);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (34, 'Adler', 'Godball', 'agodballx@walmart.com', 'Male', 42.75);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (35, 'Rudie', 'Vardey', 'rvardeyy@slashdot.org', 'Male', 83.38);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (36, 'Tracie', 'Aronson', 'taronsonz@dailymail.co.uk', 'Male', 98.4);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (37, 'Codi', 'Izard', 'cizard10@sakura.ne.jp', 'Female', 62.06);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (38, 'Jobyna', 'Shuttlewood', 'jshuttlewood11@army.mil', 'Female', 44.94);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (39, 'Sapphire', 'Magor', 'smagor12@shutterfly.com', 'Female', 72.58);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (40, 'Tiphanie', 'Braghini', 'tbraghini13@yolasite.com', 'Non-binary', 4.72);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (41, 'Claudio', 'Guiso', 'cguiso14@dailymail.co.uk', 'Male', 25.92);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (42, 'Cindee', 'Mann', 'cmann15@meetup.com', 'Female', 68.93);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (43, 'Kelcie', 'Stollenbeck', 'kstollenbeck16@statcounter.com', 'Female', 50.61);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (44, 'Carrie', 'Dewen', 'cdewen17@umn.edu', 'Female', 56.3);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (45, 'Georgi', 'Fleckno', 'gfleckno18@printfriendly.com', 'Male', 20.48);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (46, 'Ty', 'Challener', 'tchallener19@indiatimes.com', 'Male', 23.57);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (47, 'Fraser', 'StrAND', 'fstrand1a@nhs.uk', 'Male', 60.49);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (48, 'Doreen', 'Sherrum', 'dsherrum1b@soup.io', 'Female', 1.55);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (49, 'kelleher1c@un.org', 'Female', 57.85);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (50, 'Jordana', 'Allston', 'jallston1d@umich.edu', 'Female', 83.38);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (51, 'Colan', 'Cauldfield', 'ccauldfield1e@deliciousdays.com', 'Male', 72.14);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (52, 'Cathee', 'Knoble', 'cknoble1f@fema.gov', 'Female', 83.96);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (53, 'Solly', 'Tschierasche', 'stschierasche1g@merriam-webster.com', 'Male', 88.34);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (54, 'Halette', 'McLaine', 'hmclaine1h@parallels.com', 'Female', 10.63);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (55, 'Leanor', 'Greenhalgh', 'lgreenhalgh1i@hatena.ne.jp', 'Female', 28.69);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (56, 'Jocelyn', 'Rolfo', 'jrolfo1j@twitter.com', 'Female', 31.48);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (57, 'Tudor', 'Popov', 'tpopov1k@sun.com', 'Male', 54.8);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (58, 'Elysha', 'O''Reilly', 'eoreilly1l@feedburner.com', 'Female', 22.44);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (59, 'Kristofor', 'Ronchi', 'kronchi1m@cbc.ca', 'Polygender', 23.6);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (60, 'Georgie', 'Gillebride', 'ggillebride1n@drupal.org', 'Female', 27.24);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (61, 'Devinne', 'Andryushin', 'dandryushin1o@elegantthemes.com', 'Female', 73.09);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (62, 'Arlyn', 'Gregoletti', 'agregoletti1p@t-online.de', 'Female', 22.59);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (63, 'Hendrik', 'Hanhart', 'hhanhart1q@yandex.ru', 'Male', 20.26);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (64, 'Obidiah', 'Oldam', 'ooldam1r@shop-pro.jp', 'Male', 14.8);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (65, 'Willy', 'Trinkwon', 'wtrinkwon1s@bluehost.com', 'Male', 76.19);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (66, 'Kora', 'Nussen', 'knussen1t@illinois.edu', 'Female', 21.93);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (67, 'Cart', 'Scherme', 'cscherme1u@msu.edu', 'Male', 42.04);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (68, 'Hynda', 'Corah', 'hcorah1v@irs.gov', 'Female', 61.14);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (69, 'Perry', 'Chazelle', 'pchazelle1w@multiply.com', 'Male', 92.52);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (70, 'Wesley', 'Gerlts', 'wgerlts1x@geocities.jp', 'Male', 9.37);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (71, 'Karee', 'McCosker', 'kmccosker1y@paypal.com', 'Female', 7.69);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (72, 'Deni', 'O''Halloran', 'dohalloran1z@dell.com', 'Female', 14.58);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (73, 'Arabelle', 'Heyns', 'aheyns20@eepurl.com', 'Genderqueer', 61.96);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (74, 'Cleopatra', 'Balsdon', 'cbalsdon21@telegraph.co.uk', 'Female', 76.51);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (75, 'Olva', 'Poad', 'opoad22@utexas.edu', 'Female', 23.22);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (76, 'Eartha', 'Beverley', 'ebeverley23@nba.com', 'Female', 22.17);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (77, 'Elbert', 'Reeken', 'ereeken24@soup.io', 'Genderfluid', 55.18);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (78, 'Rees', 'Cooke', 'rcooke25@accuweather.com', 'Male', 49.74);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (79, 'Mattias', 'Oselton', 'moselton26@wunderground.com', 'Male', 2.17);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (80, 'Bambi', 'Bampkin', 'bbampkin27@furl.net', 'Female', 73.46);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (81, 'Alina', 'Tylor', 'atylor28@amazon.co.jp', 'Female', 45.81);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (82, 'Molly', 'Harral', 'mharral29@1688.com', 'Female', 2.03);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (83, 'Tabina', 'Atwell', 'tatwell2a@arstechnica.com', 'Female', 18.44);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (84, 'Goran', 'O''Mullaney', 'gomullaney2b@blinklist.com', 'Male', 21.2);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (85, 'Ware', 'Stiegars', 'wstiegars2c@imgur.com', 'Male', 46.14);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (86, 'Kelsey', 'Thumann', 'kthumann2d@tuttocitta.it', 'Male', 79.69);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (87, 'Kirsteni', 'Johnsey', 'kjohnsey2e@xinhuanet.com', 'Female', 36.76);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (88, 'Melvyn', 'Guppey', 'mguppey2f@nhs.uk', 'Male', 18.23);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (89, 'Stacia', 'Abeau', 'sabeau2g@nsw.gov.au', 'Female', 73.56);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (90, 'Trent', 'O''Cannavan', 'tocannavan2h@cyberchimps.com', 'Male', 96.4);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (91, 'El', 'Scarbarrow', 'escarbarrow2i@imgur.com', 'Male', 7.82);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (92, 'Gretna', 'Cowell', 'gcowell2j@skype.com', 'Female', 97.72);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (93, 'Sashenka', 'Whitfeld', 'swhitfeld2k@comcast.net', 'Female', 55.96);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (94, 'Beilul', 'Andrieux', 'bandrieux2l@earthlink.net', 'Female', 9.82);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (95, 'Dwayne', 'Southerill', 'dsoutherill2m@accuweather.com', 'Male', 56.53);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (96, 'Ashil', 'Sprott', 'asprott2n@51.la', 'Female', 99.49);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (97, 'Raymond', 'Wadeson', 'rwadeson2o@spiegel.de', 'Male', 84.07);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (98, 'Fionna', 'Britney', 'fbritney2p@si.edu', 'Female', 94.25);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (99, 'Christian', 'Vaulkhard', 'cvaulkhard2q@blog.com', 'Bigender', 67.7);
insert into opilane (opilaneID, eesnimi, perenimi, epost, sugu, stip) values (100, 'Izabel', 'Bilborough', 'ibilborough2r@ovh.net', 'Female', 47.85);

select * from opilane

--kuva ainult kaks veergu (столбца) tabelist opilane.
select perenimi, stip from opilane
--kuva kolm esimest veergu (столбца) ja sorteeri andmed stip järgi.
--kasvavas järjekorras (в порядке возрастания)
--kahanevas järjekorras (в порядке убывания)


--KASVAV JÄRJEKORD A-->Z
SELECT opilaneID, eesnimi, perenimi,stip FROM opilane ORDER BY STIP;


--KAHANEV JÄRJEKORD добавляем (DESC - DESCENDING) в конце Z-->A
SELECT opilaneID, eesnimi, perenimi,stip FROM opilane ORDER BY STIP DESC;


--ülesanne
--kuva eesnimi mis on soorteeritud kahanevas järjekorras
SELECT eesnimi FROM opilane ORDER BY eesnimi desc;



--2 ÜLESANNE --
--Võrdlused

-- näita eesnimed, mis algavad B tähega
SELECT eesnimi FROM opilane WHERE eesnimi LIKE 'b%';

-- näita eesnimi ja perenimi mis algavad B Tähega
SELECT eesnimi, perenimi FROM opilane WHERE eesnimi LIKE 'b%' or perenimi LIKE 'b%';

--näita õpilased, kellel eesnimed ja perenimed algavad B Tähega 
SELECT eesnimi, perenimi FROM opilane WHERE eesnimi LIKE 'B%' AND perenimi LIKE 'B%';

--näita eesnimed, kellel eesimene ja viimane täht on sama
SELECT eesnimi, perenimi FROM opilane WHERE LEFT(eesnimi, 1)=RIGHT(eesnimi,1)


-- ÜLESANNE 3--
-- näita opilased, kelle stip on > 50 ja väiksem kui 70
SELECT perenimi, stip FROM opilane where stip > 50 AND stip < 70

-- näita opilased, kelle stip on > 50 ja väiksem kui 70 ja päringus sorteerimine perenime kasvav A-->Z
SELECT perenimi, stip FROM opilane where stip BETWEEN 50 AND 70 ORDER BY perenimi


-- AGREGAAT FUNKTSIOONID COUNT, SUM, AVG, MIN, MAX --
-- leia õpilaste arv
SELECT COUNT(*) AS 'ÕPILASTE ARV' FROM opilane

-- leia keskmine stip
SELECT AVG(stip) AS 'KESKMINE STIP' FROM opilane

-- näita 5 õpilast kõige suurema stipiga
SELECT TOP 5 perenimi, stip FROM opilane ORDER BY stip DESC


--XAMPP kasutame TOP asemel LIMIT
SELECT perenimi, stip FROM opilane ORDER BY stip DESC LIMIT 5


--kombineerime tingimused
-- eesnimed sisaldavad A, stip (60;70)
SELECT eesnimi, stip FROM opilane WHERE(stip BETWEEN 60 AND 70) AND ((eesnimi LIKE '%a%') OR (eesnimi LIKE 'a%') OR (eesnimi LIKE '%a'));
